In [19]:
import numpy as np

# Faire un systeme de recommandation de film:

# Créer quelques utilisateurs type
# Créer une fonction permettant d'obtenir le top K film pour un utilisateur donné
# Afficher la liste


def softmax_stable(x):
    return np.exp(x - np.max(x)) / np.exp(x - np.max(x)).sum()


# Créer un tableau représentant les gouts de l'utilisateur
# 1ere Action
# 2eme Romantique
# 3eme Drame
# 4eme Policier
# 5eme Documentaire
userTaste = softmax_stable(np.array([10, 2, 3, 40, 5]))  # Gouts Utilisateur

# Créer une liste de film:
filmDataset = [
    (np.array([1, 2, 40, 20, 1]), "Film Policier 1"),
    (np.array([0, 2, 2, 20, 5]), "Film Policier 2"),
    (np.array([20, 5, 1, 30, 0]), "Film Romantique 1"),
    (np.array([20, 1, 40, 10, 20]), "Film Drame 1"),
    (np.array([30, 3, 1, 20, 50]), "Film Documentaire 1"),
    (np.array([10, 2, 3, 40, 5]), "Film Documentaire 2"),
]

results = []

maxedUserTaste = softmax_stable(userTaste)

for film in filmDataset:
    softedFilm = softmax_stable(film[0])
    kotFilm = np.dot(softedFilm, maxedUserTaste)
    results.append((kotFilm, film[1]))

# Afficher la liste des films triés par ordre de pertinence
sorted_results = sorted(results, key=lambda x: x[0], reverse=True)

# Afficher les 3 premiers
print(sorted_results)




[(0.4046096751916371, 'Film Documentaire 2'), (0.40460958863580443, 'Film Policier 2'), (0.4045980641340586, 'Film Romantique 1'), (0.14884758172924614, 'Film Policier 1'), (0.1488475812021052, 'Film Documentaire 1'), (0.14884758120210512, 'Film Drame 1')]


In [21]:
# Créer un dataset aléatoire de 15 vecteurs (blue)
blue = np.random.random((15, 5))
# Créer un second dataset aléatoire de 15 vecteurs (orange)
orange = np.random.random((15, 5))

newSample = np.random.random((5))


def manhattanDist(a, b):
    return np.absolute(a - b).sum()


# Créer une fonction 'applyKNN' qui prend en parametre le dataset complet, le nouveau sample à classifier, le nombre de plus proche voisin (k)

# Algorithme du KNN
# 1) calculer les distances entre le nouveau sample et tous les points du dataset
# 2) Stocker les distances (et leur groupe d'appartenance) dans un tableau
# 3) Trier le tableau par ordre croissant
# 4) Extraire de ce tableau les 'k' premiers éléments.
def applyKNN(newSample, k):
    distancesToBlue = []
    distancesToOrange = []
    for set in blue:
        distancesToBlue.append(manhattanDist(set, newSample))
    for set in orange:
        distancesToOrange.append(manhattanDist(set, newSample))


# La fonction s'utilise comme suit:
# group = applyKNN(dataset,newSample,5)
# print(group) -> affiche blue ou orange

[[0.38758128 0.98096621 0.39559009 0.04365559 0.53647848]
 [0.22470617 0.49618682 0.42483405 0.00100123 0.57062094]
 [0.24476579 0.47600278 0.17709252 0.06555377 0.77442024]
 [0.78852482 0.66609754 0.62580208 0.15363782 0.37082947]
 [0.16076081 0.3883116  0.31039925 0.09490316 0.59526582]
 [0.50738697 0.3576538  0.03744637 0.17780495 0.70760881]
 [0.98213461 0.23113588 0.75124262 0.06061143 0.24422026]
 [0.72935881 0.88901732 0.73008453 0.67868881 0.91364592]
 [0.62896009 0.20354021 0.33214247 0.61789318 0.69512841]
 [0.16930757 0.54566456 0.82813639 0.18914027 0.9106055 ]
 [0.36291134 0.03670983 0.0564752  0.59724219 0.29831395]
 [0.3436509  0.97431442 0.00502373 0.50480335 0.05202182]
 [0.85425205 0.59487451 0.92931238 0.75641997 0.25556263]
 [0.53817833 0.77733038 0.07159315 0.84670872 0.86850954]
 [0.00186931 0.75723307 0.66414741 0.92252146 0.96221646]]
